<a href="https://colab.research.google.com/github/atsayansach/Data-Analytics-Portfolio/blob/main/studentanalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Run this cell once whenever you (re)connect to the runtime.

# 1. Install any libraries that are NOT built into Colab - quiet affects how much text you see during installation.

!pip install pandas matplotlib seaborn --quiet

# 2. Import all the core libraries you’ll use

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 3. Global display options (optional)

pd.set_option("display.max_rows", 10)
sns.set(style="whitegrid")

print("Setup complete")

Setup complete

In [ ]:
# Connect/Mount this notebook to your Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from google.colab import files
import pandas as pd
uploaded = files.upload()  # you chose "student.csv from choose files – below tab"
full_path = '/content/student.csv' # match the name shown after upload

Saving student.csv to student.csv

In [ ]:
df= pd.read_csv('/content/student.csv')
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
df['name']

0        John Deo
1        Max Ruin
2          Arnold
3      Krish Star
4       John Mike
         ...
30    Marry Toeey
31      Binn Rott
32      Kenn Rein
33       Gain Toe
34     Rows Noump
Name: name, Length: 35, dtype: object

In [ ]:
df[['name','class']]

           name  class
0      John Deo   Four
1      Max Ruin  Three
2        Arnold  Three
3    Krish Star   Four
4     John Mike   Four
..          ...    ...
30  Marry Toeey   Four
31    Binn Rott  Seven
32    Kenn Rein    Six
33     Gain Toe  Seven
34   Rows Noump    Six

[35 rows x 2 columns]

In [ ]:
row_data = df.iloc[2]
print(row_data)

id             3
name      Arnold
class      Three
mark          55
gender      male
Name: 2, dtype: object

In [ ]:
subset_data = df.iloc[0:2, 0:2]
print(subset_data)

   id      name
0   1  John Deo
1   2  Max Ruin

In [ ]:
show = df.loc[:,'name']
print(show)

0        John Deo
1        Max Ruin
2          Arnold
3      Krish Star
4       John Mike
         ...
30    Marry Toeey
31      Binn Rott
32      Kenn Rein
33       Gain Toe
34     Rows Noump
Name: name, Length: 35, dtype: object

In [ ]:
df.loc[:,['name','class']]

           name  class
0      John Deo   Four
1      Max Ruin  Three
2        Arnold  Three
3    Krish Star   Four
4     John Mike   Four
..          ...    ...
30  Marry Toeey   Four
31    Binn Rott  Seven
32    Kenn Rein    Six
33     Gain Toe  Seven
34   Rows Noump    Six

[35 rows x 2 columns]

In [ ]:
df[df['mark'] > 80]

    id         name  class  mark  gender
1    2     Max Ruin  Three    85    male
7    8       Asruid   Five    85    male
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
..  ..          ...    ...   ...     ...
27  28    Rojj Base  Seven    86  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
34  35   Rows Noump    Six    88  female

[15 rows x 5 columns]

In [ ]:
df[(df['mark'] > 80) & (df['gender'] == 'female')]

    id        name  class  mark  gender
10  11      Ronald    Six    89  female
11  12       Recky    Six    94  female
12  13         Kty  Seven    88  female
13  14        Bigy  Seven    88  female
27  28   Rojj Base  Seven    86  female
31  32   Binn Rott  Seven    90  female
32  33   Kenn Rein    Six    96  female
34  35  Rows Noump    Six    88  female

In [ ]:
df[(df['mark'] > 80) | (df['class'] == 'Four')]

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
..  ..          ...    ...   ...     ...
27  28    Rojj Base  Seven    86  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
34  35   Rows Noump    Six    88  female

[21 rows x 5 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      35 non-null     int64
 1   name    34 non-null     object
 2   class   34 non-null     object
 3   mark    35 non-null     int64
 4   gender  33 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.5+ KB

In [ ]:
df.dropna()

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
..  ..          ...    ...   ...     ...
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

[32 rows x 5 columns]

In [ ]:
df.rename(columns={'mark':'score'}, inplace=True)

In [ ]:
df.head()

   id        name  class  score  gender
0   1    John Deo   Four     75  female
1   2    Max Ruin  Three     85    male
2   3      Arnold  Three     55    male
3   4  Krish Star   Four     60  female
4   5   John Mike   Four     60  female

In [ ]:
df['class'].value_counts()

class
Seven    10
Four      8
Six       7
Three     3
Nine      2
Five      2
Fifth     1
Eight     1
Name: count, dtype: int64

In [ ]:
df.describe()

              id      score
count  35.000000  35.000000
mean   18.000000  74.657143
std    10.246951  16.401117
min     1.000000  18.000000
25%     9.500000  62.500000
50%    18.000000  79.000000
75%    26.500000  88.000000
max    35.000000  96.000000

In [ ]:
df['score'].describe()

count    35.000000
mean     74.657143
std      16.401117
min      18.000000
25%      62.500000
50%      79.000000
75%      88.000000
max      96.000000
Name: score, dtype: float64

In [ ]:
df['score'].mean()

np.float64(74.65714285714286)

In [ ]:
print(df["id"].corr(df["score"]))

0.21158228728394565

In [ ]:
df['score'].isnull().sum()

np.int64(0)

In [ ]:
df['score'].describe()

count    35.000000
mean     74.657143
std      16.401117
min      18.000000
25%      62.500000
50%      79.000000
75%      88.000000
max      96.000000
Name: score, dtype: float64

In [ ]:
print("max is ",df['score'].max())
print("min is ",df['score'].min())
print("median is ",df['score'].median())
print("std is ",df['score'].std())

max is  96
min is  18
median is  79.0
std is  16.401116994139826

In [ ]:
df.to_csv('student_updated.csv', index=False)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

df.to_csv('/content/drive/My Drive/student_updated.csv', index=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df["name"]

0        John Deo
1        Max Ruin
2          Arnold
3      Krish Star
4       John Mike
         ...
30    Marry Toeey
31      Binn Rott
32      Kenn Rein
33       Gain Toe
34     Rows Noump
Name: name, Length: 35, dtype: object

In [ ]:
df[["name","score"]]

           name  score
0      John Deo     75
1      Max Ruin     85
2        Arnold     55
3    Krish Star     60
4     John Mike     60
..          ...    ...
30  Marry Toeey     88
31    Binn Rott     90
32    Kenn Rein     96
33     Gain Toe     69
34   Rows Noump     88

[35 rows x 2 columns]

In [ ]:
df.iloc[0:3]

   id      name  class  score  gender
0   1  John Deo   Four     75  female
1   2  Max Ruin  Three     85    male
2   3    Arnold  Three     55    male

In [ ]:
df[df["class"]=="Four"]

    id         name class  score  gender
0    1     John Deo  Four     75  female
3    4   Krish Star  Four     60  female
4    5    John Mike  Four     60  female
5    6    Alex John  Four     55    male
9   10     Big John  Four     55  female
15  16        Gimmy  Four     88    male
20  21   Babby John  Four     69  female
30  31  Marry Toeey  Four     88    male

In [ ]:
df["passed"]= df["score"]>=60
df.head()

   id        name  class  score  gender  passed
0   1    John Deo   Four     75  female    True
1   2    Max Ruin  Three     85    male    True
2   3      Arnold  Three     55    male   False
3   4  Krish Star   Four     60  female    True
4   5   John Mike   Four     60  female    True

In [ ]:
df.rename(columns={"score":"mark"}, inplace = True)

In [ ]:
df.rename(columns={"mark":"score"}, inplace = True)

In [ ]:
df.drop(columns="passed")

    id         name  class  score  gender
0    1     John Deo   Four     75  female
1    2     Max Ruin  Three     85    male
2    3       Arnold  Three     55    male
3    4   Krish Star   Four     60  female
4    5    John Mike   Four     60  female
..  ..          ...    ...    ...     ...
30  31  Marry Toeey   Four     88    male
31  32    Binn Rott  Seven     90  female
32  33    Kenn Rein    Six     96  female
33  34     Gain Toe  Seven     69    male
34  35   Rows Noump    Six     88  female

[35 rows x 5 columns]

In [ ]:
df.groupby("class")["score"].mean()

class
Eight    79.000000
Fifth    78.000000
Five     80.000000
Four     68.750000
Nine     41.500000
Seven    77.600000
Six      82.571429
Three    73.666667
Name: score, dtype: float64

In [ ]:
df.groupby("class")["id"].count()

class
Eight     1
Fifth     1
Five      2
Four      8
Nine      2
Seven    10
Six       7
Three     3
Name: id, dtype: int64

In [ ]:
df.groupby("gender")["score"].mean()

gender
female    77.312500
male      71.588235
Name: score, dtype: float64

In [ ]:
df.pivot_table(index="class", columns="gender", values="score")

gender  female  male
class
Eight      NaN  79.0
Fifth      NaN  78.0
Five       NaN  80.0
Four      63.8  77.0
Nine      65.0  18.0
Seven     81.4  73.8
Six       89.2  54.0
Three      NaN  70.0

In [ ]:
def grade_check(score):
    if score >= 85:
        return "A"
    elif score >= 70:
        return "B"
    elif score >= 60:
        return "C"
    else:
        return "D"

df["grade"] = df["score"].apply(grade_check)

df.head()

   id        name  class  score  gender  passed grade
0   1    John Deo   Four     75  female    True     B
1   2    Max Ruin  Three     85    male    True     A
2   3      Arnold  Three     55    male   False     D
3   4  Krish Star   Four     60  female    True     C
4   5   John Mike   Four     60  female    True     C

In [ ]:
df = df.sort_values("score", ascending=False)
df.head()

    id         name  class  score  gender  passed grade
32  33    Kenn Rein    Six     96  female    True     A
11  12        Recky    Six     94  female    True     A
31  32    Binn Rott  Seven     90  female    True     A
10  11       Ronald    Six     89  female    True     A
30  31  Marry Toeey   Four     88    male    True     A